spring:
  config:
    import: classpath:application-auth.yml
  datasource:
    url: jdbc:mysql://localhost:3306/service?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      add-mappings: false
  exposed:
    show-sql: true
    generate-ddl: true
logging:
  level:
    Exposed: DEBUG
