name: Build sloth-hell application

on:
  push:
    branches: [ main ]

env:
  RESOURCES_CLASSPATH: src/main/resources
  APPLICATION_AUTH_FILE_NAME: application-auth.yml
  APPLE_AUTH_KEY_DIR: src/main/resources/key
  APPLE_AUTH_KEY_FILE_NAME: AuthKey.p8
  JAR_FILE_NAME: sloth-hell.jar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker image build and push
        run: |
          cat << EOF >> ${{ env.RESOURCES_CLASSPATH }}/${{ env.APPLICATION_AUTH_FILE_NAME }}
          ${{ secrets.APPLICATION_AUTH_YML }}
          EOF
          mkdir ${{ env.APPLE_AUTH_KEY_DIR }}
          cat << EOF >> ${{ env.APPLE_AUTH_KEY_DIR }}/${{ env.APPLE_AUTH_KEY_FILE_NAME }}
          ${{ secrets.APPLE_AUTH_KEY }}
          EOF
          chmod +x gradlew
          docker build --build-arg DATE_FOR_DISABLE_CACHE=$(date +%s) --tag ${{ secrets.DOCKER_USER }}/${{ secrets.APPLICATION_NAME }} .
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.APPLICATION_NAME }}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.APPLICATION_NAME }}
            docker stop ${{ secrets.APPLICATION_NAME }}
            docker run -d --rm --name ${{ secrets.APPLICATION_NAME }} -p 80:8080 ${{ secrets.DOCKER_USER }}/${{ secrets.APPLICATION_NAME }}
